package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"syscall"
	"time"
)

// Session mirrors the schema Claude Code writes to ~/.claude/sessions/<pid>.json,
// plus the derived fields we compute at collection time (CPU, Tmux, Host).
type Session struct {
	PID        int    `json:"pid"`
	SessionID  string `json:"sessionId"`
	CWD        string `json:"cwd"`
	Status     string `json:"status"`
	WaitingFor string `json:"waitingFor"`
	Version    string `json:"version"`
	Entrypoint string `json:"entrypoint"` // "cli" for interactive, "sdk-*" for headless runs
	Name       string `json:"name"`
	NameSource string `json:"nameSource"` // "derived" = auto-generated by Claude Code; other values (e.g. "user") = user-set
	StartedAt  int64  `json:"startedAt"`  // millis since epoch
	UpdatedAt  int64  `json:"updatedAt"`  // millis since epoch; absent for headless (sdk-cli) sessions

	// Tool names the CLI that owns this session. "" is Claude Code — every
	// session file Claude Code writes, and every row a server predating this
	// field sends over the wire, decodes as claude with no migration step.
	// toolGrok (grok.go) marks a row collected from the xAI Grok CLI's own
	// registry. Action dispatch reads it to route reattestation, resume, and
	// to refuse the claude-only actions (migrate, snapshot restore).
	Tool string `json:"tool,omitempty"`

	Model         string `json:"model,omitempty"`         // last main-loop assistant model from the transcript
	ContextTokens int    `json:"contextTokens,omitempty"` // context size of that turn (input+cache tokens)
	ContextWindow int    `json:"contextWindow,omitempty"` // model context limit used to color CTX; 0 = use render.go's Claude default

	// Cumulative dollar cost from the transcript's usage, split by source:
	// CostUSD is the parent transcript (main loop), CostSubagentsUSD is the
	// summed cost of child sessions (Claude: Task-tool jsonl under
	// subagents/; Grok: each spawned child session's updates.jsonl).
	// Computed at collection time so remote rows render from the JSON as-is.
	CostUSD          float64 `json:"costUsd,omitempty"`
	CostSubagentsUSD float64 `json:"costSubagentsUsd,omitempty"`

	// TokensSpent is the cumulative API tokens (Claude: input+output+cache
	// write+cache read; Grok: sum of parent plus child-session
	// turn_completed totalTokens). 0 / omitted = unknown or none.
	TokensSpent int `json:"tokensSpent,omitempty"`

	// Disabled and Group are this host's shared per-session flags, overlaid at
	// serve/render time from its FlagsStore (session_flags.go) — never read
	// from the session file Claude Code writes. Both ride the wire so a remote
	// row shows its owning host's badge and greying; a host that predates them
	// simply omits both, which decodes as ungrouped and enabled.
	Disabled bool `json:"disabled,omitempty"`
	Group    int  `json:"group,omitempty"` // 1..9, 0 = ungrouped

	CPU          string `json:"cpu"`
	Tmux         string `json:"tmux"` // "session:win.pane" or "" if not in tmux
	TmuxAttached *int   `json:"tmuxAttached,omitempty"`

	Home string `json:"home,omitempty"` // collector's home, used for local/remote ~ collapse
	Host string `json:"-"`              // client-only remote host label

	// GitRoot is the top-level directory of the git repo containing CWD (found
	// by walking up looking for ".git"), or "" if CWD isn't inside a git repo.
	// Computed at collection time so remote rows render from the JSON as-is;
	// render.go uses it to decide between the short "<repo-name>" DIR display
	// and the full squashed-home path for non-git working directories.
	GitRoot string `json:"gitRoot,omitempty"`

	// WorktreeName is a display-only checkout label (e.g. "DR-3141") for a
	// grok row whose process cwd is still the main repo. Pickup creates
	// .claude/worktrees/<name> and edits there without rewriting the
	// registry cwd. Empty when cwd already names the worktree (dirDisplay
	// reads the path) or when no worktree can be inferred. Never rewrite CWD
	// from this field: attach, tmux and kill still use the real process dir.
	WorktreeName string `json:"worktreeName,omitempty"`
}

// IsGrok reports whether this row is an xAI Grok CLI session rather than a
// Claude Code one.
func (s Session) IsGrok() bool { return s.Tool == toolGrok }

// StatusDisplay returns the status label including the waitingFor suffix
// when relevant (e.g. "waiting:permission prompt"). Any non-empty WaitingFor
// means blocked on the user (see Waiting()), so the label always leads with
// "waiting" rather than echoing the raw Status underneath it — a mid-turn
// permission prompt has Status "busy", which would otherwise render as
// ordinary background work instead of something needing a click.
func (s Session) StatusDisplay() string {
	if s.WaitingFor != "" {
		return "waiting:" + s.WaitingFor
	}
	return s.Status
}

// Waiting reports whether the session is blocked on the user.
//
// WaitingFor is the reliable signal, not Status: Claude Code writes shapes like
// {Status: "busy", WaitingFor: "permission prompt"}, which StatusDisplay,
// sessionStatusRank and selection.go's firstIdleTarget (Tab's jump target)
// all treat as waiting via this method — never by comparing Status directly.
func (s Session) Waiting() bool { return s.WaitingFor != "" }

// NotIdle reports whether the session has active status (busy, shell,
// waiting) rather than idle or unknown — the signal for warning a user before
// an action that would interrupt it (e.g. migrate-to-attach kills the pid).
func (s Session) NotIdle() bool {
	return s.Status != "" && s.Status != "idle"
}

// ID is the stable identifier used for selection: <pid> for local rows,
// <host>:<pid> for remote.
func (s Session) ID() string {
	if s.Host == "" {
		return strconv.Itoa(s.PID)
	}
	return s.Host + ":" + strconv.Itoa(s.PID)
}

// Headless reports whether the session came from a non-interactive entrypoint
// (claude -p, Agent SDK). These never write name/status/updatedAt and vanish
// when the run finishes, so the TUI renders them dimmed.
func (s Session) Headless() bool {
	return strings.HasPrefix(s.Entrypoint, "sdk-")
}

// DisplayName resolves the label for the NAME column and whether it should
// render dimmed. Preference: user-set name → worktree dir name → derived name →
// "-". Only a name the user set themselves renders bright and wins outright;
// everything auto-derived is dimmed. A name of literally "-" is treated as
// unset (matches the column's own empty placeholder) and falls through to
// the usual chain rather than rendering bright as "-".
func (s Session) DisplayName() (label string, dimmed bool) {
	name := s.Name
	if name == "-" {
		name = ""
	}
	if name != "" && s.NameSource != "derived" {
		return name, false
	}
	if wt := worktreeName(s.CWD); wt != "" {
		return wt, true
	}
	if name != "" { // derived
		return name, true
	}
	return "-", true
}

// worktreeName extracts the worktree label from a cwd under
// .claude/worktrees/<name>/..., returning "<name>" or "" if cwd isn't one.
func worktreeName(cwd string) string {
	const marker = "/.claude/worktrees/"
	i := strings.Index(cwd, marker)
	if i < 0 {
		return ""
	}
	rest := cwd[i+len(marker):]
	if j := strings.IndexByte(rest, '/'); j >= 0 {
		rest = rest[:j]
	}
	return rest
}

// Updated returns the parsed updated-at timestamp. Headless sessions never
// write updatedAt, so fall back to startedAt rather than reporting the epoch.
func (s Session) Updated() time.Time {
	if s.UpdatedAt == 0 {
		return time.UnixMilli(s.StartedAt)
	}
	return time.UnixMilli(s.UpdatedAt)
}

// isScratchCWD reports whether cwd is /tmp, /private, or a subdirectory of
// either. Sessions launched there are short-lived scratch/automation runs
// (hooks, headless forks, one-shot scripts), not real project work, so they're
// hidden from every view.
func isScratchCWD(cwd string) bool {
	return cwd == "/tmp" || strings.HasPrefix(cwd, "/tmp/") ||
		cwd == "/private" || strings.HasPrefix(cwd, "/private/")
}

// CollectLocal reads every *.json under ~/.claude/sessions, filters out dead
// pids, and enriches each session with CPU% and tmux pane info.
func CollectLocal() ([]Session, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, err
	}
	dir := filepath.Join(home, ".claude", "sessions")
	matches, err := filepath.Glob(filepath.Join(dir, "*.json"))
	if err != nil {
		return nil, err
	}

	panes, _ := tmuxPaneMap() // best-effort: empty map if tmux not running
	ppid, cpu, err := processInfo()
	if err != nil {
		return nil, fmt.Errorf("read process tree: %w", err)
	}
	children := childrenMap(ppid)

	out := make([]Session, 0, len(matches))
	for _, p := range matches {
		s, ok := readSessionFile(p)
		if !ok {
			continue
		}
		if !sessionPIDAlive(s.PID) {
			continue
		}
		if isScratchCWD(s.CWD) {
			continue
		}
		if s.Headless() {
			continue
		}
		out = append(out, s)
	}
	// Grok CLI sessions come from their own registry (grok.go) but go through
	// the identical enrichment below, so a grok row carries the same CPU
	// reading and tmux pane address every action already depends on — attach,
	// preview, send-keys, resize and kill need no per-tool path at all.
	//
	// A pid claude still has a session file for wins outright. Claude does not
	// delete that file when the process exits, so a pid it once used and grok
	// now owns would otherwise produce two rows whose Session.ID() is the same
	// "<pid>" — and selection, kill routing and the TUI's row bookkeeping all
	// key on that id being unique. Claude's row is the one to keep: it carries
	// a user-set name and a real status, where the grok row for a recycled pid
	// is the one more likely to be wrong.
	claudePIDs := make(map[int]bool, len(out))
	for _, s := range out {
		claudePIDs[s.PID] = true
	}
	for _, g := range collectGrokLocal(home) {
		if claudePIDs[g.PID] {
			continue
		}
		out = append(out, g)
	}

	for i := range out {
		s := &out[i]
		if c, ok := sumProcessTreeCPU(s.PID, cpu, children); ok {
			s.CPU = c
		} else {
			s.CPU = "-"
		}
		if pane, found := walkTmuxPane(s.PID, panes, ppid); found {
			s.Tmux = pane.Location
			s.TmuxAttached = pane.Attached
		}
		s.Home = home
		s.GitRoot = gitRootFor(s.CWD)
		if s.IsGrok() {
			// Model came from grok's own summary.json. Context comes from
			// signals.json (filled in grokSessionFrom). Cost comes from
			// updates.jsonl in grokSessionFrom. Skip so a claude transcript
			// cannot overwrite model/CTX/cost.
			continue
		}
		if p := findTranscript(home, s.SessionID); p != "" {
			m := cachedMeta(p)
			s.Model = m.Model
			s.ContextTokens = m.ContextTokens
			s.CostUSD, s.CostSubagentsUSD, s.TokensSpent = scanSessionCost(p)
		}
	}
	// Sort by cwd (case-insensitive), newest-started first as tiebreaker. This
	// is the server-side default; the client re-sorts per its own mode.
	SortSessions(out, "dir", false)
	return out, nil
}

// CollectLocalLite reads every *.json under ~/.claude/sessions and applies the
// same liveness and visibility filters as CollectLocal, but skips CPU, tmux,
// and transcript enrichment entirely.
//
// Grok sessions are deliberately NOT included. This feeds the account-switch
// warning about sessions still holding the outgoing Anthropic token
// (switchSessionWarnings, account.go), and a grok session holds no Anthropic
// credential at all — listing one there would warn about a process that
// cannot possibly clobber the credential being installed.
//
// The notification ticker runs this every couple of seconds and needs only
// identity and status. CollectLocal's per-session transcript scans (cost,
// model, context tokens, running subagents) are far too expensive at that
// cadence. Results are unsorted: callers key them by SessionID.
func CollectLocalLite() ([]Session, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, err
	}
	matches, err := filepath.Glob(filepath.Join(home, ".claude", "sessions", "*.json"))
	if err != nil {
		return nil, err
	}
	out := make([]Session, 0, len(matches))
	for _, p := range matches {
		s, ok := readSessionFile(p)
		if !ok {
			continue
		}
		if !sessionPIDAlive(s.PID) || isScratchCWD(s.CWD) || s.Headless() {
			continue
		}
		s.Home = home
		out = append(out, s)
	}
	return out, nil
}

// sessionStatusRank buckets a session for "status" mode ordering: sessions
// waiting on the user first, then idle, shell, busy, and everything else
// (unknown/blank status).
func sessionStatusRank(s Session) int {
	if s.WaitingFor != "" {
		return 0
	}
	switch strings.ToLower(s.Status) {
	case "idle":
		return 1
	case "shell":
		return 2
	case "busy":
		return 3
	default:
		return 4
	}
}

// SortSessions orders rows in place, stably, per the given mode:
//
//	dir         cwd asc (case-insensitive), StartedAt desc tiebreak
//	status      waiting > idle > shell > busy > other, Updated() asc tiebreak (oldest first)
//	created     StartedAt desc; created-asc: StartedAt asc
//	updated     Updated() desc; updated-asc: Updated() asc
//
// An unknown mode is treated as "dir".
func sessionLess(a, b Session, mode string) bool {
	if a.Disabled != b.Disabled {
		return !a.Disabled
	}
	switch mode {
	case "status":
		ra, rb := sessionStatusRank(a), sessionStatusRank(b)
		if ra != rb {
			return ra < rb
		}
		return a.Updated().Before(b.Updated())
	case "created":
		return a.StartedAt > b.StartedAt
	case "created-asc":
		return a.StartedAt < b.StartedAt
	case "updated":
		return a.Updated().After(b.Updated())
	case "updated-asc":
		return a.Updated().Before(b.Updated())
	default:
		ca, cb := strings.ToLower(a.CWD), strings.ToLower(b.CWD)
		if ca != cb {
			return ca < cb
		}
		return a.StartedAt > b.StartedAt
	}
}

// groupSortRank maps a group number to its group-first sort key: groups 1-9
// rank by their own number; ungrouped (0, or any out-of-range value) ranks
// last (10), sinking below every named group.
func groupSortRank(group int) int {
	if group < 1 || group > 9 {
		return 10
	}
	return group
}

// sessionLessGrouped wraps sessionLess with an optional group-first tier: when
// groupSort is on, rows rank by group number ascending first, with ungrouped
// rows sinking to the bottom — checked ahead of sessionLess's own
// disabled-last rule, so a disabled row sorts last *within its own group*
// rather than sinking below every group. Ties (same group, or groupSort off)
// fall through to sessionLess, which still applies disabled-last and the
// per-mode comparison.
func sessionLessGrouped(a, b Session, mode string, groupSort bool) bool {
	if groupSort {
		ra, rb := groupSortRank(a.Group), groupSortRank(b.Group)
		if ra != rb {
			return ra < rb
		}
	}
	return sessionLess(a, b, mode)
}

// SortSessions orders rows in place, stably, per mode (see sessionLess). When
// groupSort is true, rows rank by group number 1-9 ascending first, with
// ungrouped sessions sinking last, before the normal per-mode comparison
// breaks ties.
func SortSessions(rows []Session, mode string, groupSort bool) {
	sort.SliceStable(rows, func(i, j int) bool {
		return sessionLessGrouped(rows[i], rows[j], mode, groupSort)
	})
}

func readSessionFile(path string) (Session, bool) {
	data, err := os.ReadFile(path)
	if err != nil {
		return Session{}, false
	}
	var s Session
	if err := json.Unmarshal(data, &s); err != nil {
		return Session{}, false
	}
	// The shared flags are the host's to set, not the session file's: zero them
	// so a hand-edited session file cannot inject a badge or a greyed row.
	s.Disabled = false
	s.Group = 0
	if s.PID == 0 {
		return Session{}, false
	}
	return s, true
}

// pidAlive returns true if signal 0 to the pid succeeds (process exists and
// we have permission to signal it).
func pidAlive(pid int) bool {
	return syscall.Kill(pid, 0) == nil
}

// sessionPIDAlive is the liveness check the claude collectors apply, the
// counterpart of grok.go's grokPIDAlive. A package var for the same reason:
// a test that describes a session list with made-up pids must be able to say
// which of them are running, for both tools, instead of depending on whichever
// pids happen to exist on the machine running `go test`. Production always
// leaves it as pidAlive.
var sessionPIDAlive = pidAlive
