package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"syscall"
	"time"
)

// Session mirrors the schema Claude Code writes to ~/.claude/sessions/<pid>.json,
// plus the derived fields we compute at collection time (CPU, Tmux, Host).
type Session struct {
	PID        int    `json:"pid"`
	SessionID  string `json:"sessionId"`
	CWD        string `json:"cwd"`
	Status     string `json:"status"`
	WaitingFor string `json:"waitingFor"`
	Version    string `json:"version"`
	Entrypoint string `json:"entrypoint"` // "cli" for interactive, "sdk-*" for headless runs
	Name       string `json:"name"`
	NameSource string `json:"nameSource"` // "derived" = auto-generated by Claude Code; other values (e.g. "user") = user-set
	StartedAt  int64  `json:"startedAt"`  // millis since epoch
	UpdatedAt  int64  `json:"updatedAt"`  // millis since epoch; absent for headless (sdk-cli) sessions

	Model         string `json:"model,omitempty"`         // last main-loop assistant model from the transcript
	ContextTokens int    `json:"contextTokens,omitempty"` // context size of that turn (input+cache tokens)

	// Cumulative dollar cost from the transcript's usage, split by source:
	// CostUSD is the parent transcript (main loop), CostSubagentsUSD is the
	// summed cost of the session's Task-tool subagent transcripts. Computed at
	// collection time so remote rows render from the JSON as-is.
	CostUSD          float64 `json:"costUsd,omitempty"`
	CostSubagentsUSD float64 `json:"costSubagentsUsd,omitempty"`

	// AgentsRunning is the number of currently running Task/Agent-tool
	// subagents (incl. nested), per scanSessionAgents. Computed at collection
	// time so remote rows render from the JSON as-is.
	AgentsRunning int `json:"agentsRunning,omitempty"`

	CPU  string `json:"cpu"`
	Tmux string `json:"tmux"` // "session:win.pane" or "" if not in tmux

	Home string `json:"home,omitempty"` // collector's home, used for local/remote ~ collapse
	Host string `json:"-"`              // client-only remote host label
}

// StatusDisplay returns the status label including the waitingFor suffix
// when relevant (e.g. "waiting:permission prompt").
func (s Session) StatusDisplay() string {
	if s.WaitingFor != "" {
		return s.Status + ":" + s.WaitingFor
	}
	return s.Status
}

// ID is the stable identifier used for selection: <pid> for local rows,
// <host>:<pid> for remote.
func (s Session) ID() string {
	if s.Host == "" {
		return strconv.Itoa(s.PID)
	}
	return s.Host + ":" + strconv.Itoa(s.PID)
}

// Headless reports whether the session came from a non-interactive entrypoint
// (claude -p, Agent SDK). These never write name/status/updatedAt and vanish
// when the run finishes, so the TUI renders them dimmed.
func (s Session) Headless() bool {
	return strings.HasPrefix(s.Entrypoint, "sdk-")
}

// DisplayName resolves the label for the NAME column and whether it should
// render dimmed. Preference: user-set name → worktree dir name → derived name →
// "-". Only a name the user set themselves renders bright and wins outright;
// everything auto-derived is dimmed.
func (s Session) DisplayName() (label string, dimmed bool) {
	if s.Name != "" && s.NameSource != "derived" {
		return s.Name, false
	}
	if wt := worktreeName(s.CWD); wt != "" {
		return wt, true
	}
	if s.Name != "" { // derived
		return s.Name, true
	}
	return "-", true
}

// worktreeName extracts the worktree label from a cwd under
// .claude/worktrees/<name>/..., returning "<name>" or "" if cwd isn't one.
func worktreeName(cwd string) string {
	const marker = "/.claude/worktrees/"
	i := strings.Index(cwd, marker)
	if i < 0 {
		return ""
	}
	rest := cwd[i+len(marker):]
	if j := strings.IndexByte(rest, '/'); j >= 0 {
		rest = rest[:j]
	}
	return rest
}

// Updated returns the parsed updated-at timestamp. Headless sessions never
// write updatedAt, so fall back to startedAt rather than reporting the epoch.
func (s Session) Updated() time.Time {
	if s.UpdatedAt == 0 {
		return time.UnixMilli(s.StartedAt)
	}
	return time.UnixMilli(s.UpdatedAt)
}

// CollectLocal reads every *.json under ~/.claude/sessions, filters out dead
// pids, and enriches each session with CPU% and tmux pane info.
func CollectLocal() ([]Session, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, err
	}
	dir := filepath.Join(home, ".claude", "sessions")
	matches, err := filepath.Glob(filepath.Join(dir, "*.json"))
	if err != nil {
		return nil, err
	}

	panes, _ := tmuxPaneMap() // best-effort: empty map if tmux not running
	ppid, cpu, err := processInfo()
	if err != nil {
		return nil, fmt.Errorf("read process tree: %w", err)
	}

	out := make([]Session, 0, len(matches))
	for _, p := range matches {
		s, ok := readSessionFile(p)
		if !ok {
			continue
		}
		if !pidAlive(s.PID) {
			continue
		}
		if c, ok := cpu[s.PID]; ok {
			s.CPU = c
		} else {
			s.CPU = "-"
		}
		s.Tmux = walkTmuxPane(s.PID, panes, ppid)
		s.Home = home
		if p := findTranscript(home, s.SessionID); p != "" {
			m := cachedMeta(p)
			s.Model = m.Model
			s.ContextTokens = m.ContextTokens
			s.CostUSD, s.CostSubagentsUSD = scanSessionCost(p)
			s.AgentsRunning = scanSessionAgents(p, time.Now())
		}
		out = append(out, s)
	}
	// Sort by cwd (case-insensitive), newest-started first as tiebreaker. This
	// is the server-side default; the client re-sorts per its own mode.
	SortSessions(out, "dir")
	return out, nil
}

// SortSessions orders rows in place, stably, per the given mode:
//
//	dir         cwd asc (case-insensitive), StartedAt desc tiebreak
//	created     StartedAt desc; created-asc: StartedAt asc
//	updated     Updated() desc; updated-asc: Updated() asc
//
// An unknown mode is treated as "dir".
func SortSessions(rows []Session, mode string) {
	switch mode {
	case "created":
		sort.SliceStable(rows, func(i, j int) bool {
			return rows[i].StartedAt > rows[j].StartedAt
		})
	case "created-asc":
		sort.SliceStable(rows, func(i, j int) bool {
			return rows[i].StartedAt < rows[j].StartedAt
		})
	case "updated":
		sort.SliceStable(rows, func(i, j int) bool {
			return rows[i].Updated().After(rows[j].Updated())
		})
	case "updated-asc":
		sort.SliceStable(rows, func(i, j int) bool {
			return rows[i].Updated().Before(rows[j].Updated())
		})
	default: // "dir"
		sort.SliceStable(rows, func(i, j int) bool {
			ci, cj := strings.ToLower(rows[i].CWD), strings.ToLower(rows[j].CWD)
			if ci != cj {
				return ci < cj
			}
			return rows[i].StartedAt > rows[j].StartedAt
		})
	}
}

func readSessionFile(path string) (Session, bool) {
	data, err := os.ReadFile(path)
	if err != nil {
		return Session{}, false
	}
	var s Session
	if err := json.Unmarshal(data, &s); err != nil {
		return Session{}, false
	}
	if s.PID == 0 {
		return Session{}, false
	}
	return s, true
}

// pidAlive returns true if signal 0 to the pid succeeds (process exists and
// we have permission to signal it).
func pidAlive(pid int) bool {
	return syscall.Kill(pid, 0) == nil
}
